# Generated by Django 2.1.5 on 2019-03-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hashtest',
            },
        ),
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'otheruser',
            },
        ),
        migrations.CreateModel(
            name='SelfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'selfuser',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.CharField(max_length=10)),
                ('stu_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'studentinfo',
            },
        ),
        migrations.CreateModel(
            name='StudentTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=60)),
                ('stu_01', models.CharField(default='0', max_length=5, null=True)),
                ('stu_02', models.CharField(default='0', max_length=5, null=True)),
                ('stu_03', models.CharField(default='0', max_length=5, null=True)),
                ('stu_04', models.CharField(default='0', max_length=5, null=True)),
                ('stu_05', models.CharField(default='0', max_length=5, null=True)),
                ('stu_06', models.CharField(default='0', max_length=5, null=True)),
                ('stu_07', models.CharField(default='0', max_length=5, null=True)),
                ('stu_08', models.CharField(default='0', max_length=5, null=True)),
                ('stu_09', models.CharField(default='0', max_length=5, null=True)),
                ('stu_10', models.CharField(default='0', max_length=5, null=True)),
                ('stu_11', models.CharField(default='0', max_length=5, null=True)),
                ('stu_12', models.CharField(default='0', max_length=5, null=True)),
                ('stu_13', models.CharField(default='0', max_length=5, null=True)),
                ('stu_14', models.CharField(default='0', max_length=5, null=True)),
                ('stu_15', models.CharField(default='0', max_length=5, null=True)),
                ('stu_16', models.CharField(default='0', max_length=5, null=True)),
                ('stu_17', models.CharField(default='0', max_length=5, null=True)),
                ('stu_18', models.CharField(default='0', max_length=5, null=True)),
                ('stu_19', models.CharField(default='0', max_length=5, null=True)),
                ('stu_20', models.CharField(default='0', max_length=5, null=True)),
                ('stu_21', models.CharField(default='0', max_length=5, null=True)),
                ('stu_22', models.CharField(default='0', max_length=5, null=True)),
                ('stu_23', models.CharField(default='0', max_length=5, null=True)),
                ('stu_24', models.CharField(default='0', max_length=5, null=True)),
                ('stu_25', models.CharField(default='0', max_length=5, null=True)),
                ('stu_26', models.CharField(default='0', max_length=5, null=True)),
                ('stu_27', models.CharField(default='0', max_length=5, null=True)),
                ('stu_28', models.CharField(default='0', max_length=5, null=True)),
                ('stu_29', models.CharField(default='0', max_length=5, null=True)),
                ('stu_30', models.CharField(default='0', max_length=5, null=True)),
                ('stu_31', models.CharField(default='0', max_length=5, null=True)),
                ('stu_32', models.CharField(default='0', max_length=5, null=True)),
            ],
            options={
                'db_table': 'studenttestinfo',
            },
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'userip',
            },
        ),
    ]
