# Generated by Django 2.1.5 on 2019-02-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='test3',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
