# Generated by Django 2.1.5 on 2019-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='username',
            field=models.CharField(default='*', max_length=30, null=True),
        ),
    ]
