# Generated by Django 2.1.5 on 2019-02-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_studentinfo_test3'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=60)),
                ('stu_1', models.IntegerField(default=0, max_length=10)),
                ('stu_2', models.IntegerField(default=0, max_length=10)),
                ('stu_3', models.IntegerField(default=0, max_length=10)),
                ('stu_4', models.IntegerField(default=0, max_length=10)),
                ('stu_5', models.IntegerField(default=0, max_length=10)),
                ('stu_6', models.IntegerField(default=0, max_length=10)),
                ('stu_7', models.IntegerField(default=0, max_length=10)),
                ('stu_8', models.IntegerField(default=0, max_length=10)),
                ('stu_9', models.IntegerField(default=0, max_length=10)),
                ('stu_10', models.IntegerField(default=0, max_length=10)),
                ('stu_11', models.IntegerField(default=0, max_length=10)),
                ('stu_12', models.IntegerField(default=0, max_length=10)),
                ('stu_13', models.IntegerField(default=0, max_length=10)),
                ('stu_14', models.IntegerField(default=0, max_length=10)),
                ('stu_15', models.IntegerField(default=0, max_length=10)),
                ('stu_16', models.IntegerField(default=0, max_length=10)),
                ('stu_17', models.IntegerField(default=0, max_length=10)),
                ('stu_18', models.IntegerField(default=0, max_length=10)),
                ('stu_19', models.IntegerField(default=0, max_length=10)),
                ('stu_20', models.IntegerField(default=0, max_length=10)),
                ('stu_21', models.IntegerField(default=0, max_length=10)),
                ('stu_22', models.IntegerField(default=0, max_length=10)),
                ('stu_23', models.IntegerField(default=0, max_length=10)),
                ('stu_24', models.IntegerField(default=0, max_length=10)),
                ('stu_25', models.IntegerField(default=0, max_length=10)),
                ('stu_26', models.IntegerField(default=0, max_length=10)),
                ('stu_27', models.IntegerField(default=0, max_length=10)),
                ('stu_28', models.IntegerField(default=0, max_length=10)),
                ('stu_29', models.IntegerField(default=0, max_length=10)),
                ('stu_30', models.IntegerField(default=0, max_length=10)),
                ('stu_31', models.IntegerField(default=0, max_length=10)),
                ('stu_32', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
