# Generated by Django 2.1.5 on 2019-02-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20190212_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='test3',
        ),
    ]
