# Generated by Django 2.1.5 on 2019-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_remove_studentinfo_test3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_1',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_10',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_11',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_12',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_13',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_14',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_15',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_16',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_17',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_18',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_19',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_2',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_20',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_21',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_22',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_23',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_24',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_25',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_26',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_27',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_28',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_29',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_3',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_30',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_31',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_32',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_4',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_5',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_6',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_7',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_8',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='studenttestinfo',
            name='stu_9',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
