# Generated by Django 2.1.5 on 2019-02-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20190212_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtest',
            name='test_hash',
        ),
    ]
