# Generated by Django 2.1.5 on 2019-02-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_remove_hashtest_test_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtest',
            old_name='test_title',
            new_name='test',
        ),
    ]
