# Generated by Django 2.1.5 on 2019-02-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20190212_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_1',
            new_name='stu_01',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_2',
            new_name='stu_02',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_3',
            new_name='stu_03',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_4',
            new_name='stu_04',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_5',
            new_name='stu_05',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_6',
            new_name='stu_06',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_7',
            new_name='stu_07',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_8',
            new_name='stu_08',
        ),
        migrations.RenameField(
            model_name='studenttestinfo',
            old_name='stu_9',
            new_name='stu_09',
        ),
    ]
